/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "forca.h"


void
game_forca_1(char *host)
{
	CLIENT *clnt;
	game_response  *start_res;
	game  start_game_1_arg;

	game_response *res;

	clnt = clnt_create (host, GAME_FORCA, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	start_res = start_game_1(&start_game_1_arg, clnt);
	if (start_res == (game_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	if(start_res->player_id == -1){
		clnt_perror (clnt, "Room fully crowded");
		exit(1);
	}
	printf("Seu id e: %i\n", start_res->player_id);

	game game_res = start_res->g;
	char try_char;
	while (1){
		printf("Palavra: %s\n", game_res.hidden_word);
		printf("Dica: %s\n", game_res.tip);
		printf("Sua tentativa: ");
		scanf("%c", &try_char);
		while (getchar() != '\n');
		game try;
		try.player_trying = try_char;
		try.id_player_trying = start_res->player_id;

		res = trying_1(&try, clnt);
		if (res == (game_response *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		memcpy((void*)(&game_res), res, sizeof(game));

		printf("\n");
	}
	
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	game_forca_1 (host);
exit (0);
}
