/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "forca.h"

float *
sum_100_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("-------------------------------------------\n");
	printf("                 SERVICO RPC               \n");
	printf("-------------------------------------------\n");
	printf("Chamando operacao para os operandos %.2f e %.2f\n", argp->n1, argp->n2);
	//O servidor vai fazer algo com os valores passados na chamada
	result = argp->n1 + argp->n2;
	printf("result %f\n", result);

	return &result;
}
