/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FORCA_H_RPCGEN
#define _FORCA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct game {
	int players_slots[4];
	int players_in_room;
	char current_word[50];
	char hidden_word[50];
	char tip[100];
	int can_go;
	int turn;
};
typedef struct game game;

struct start_game_response {
	game g;
	int player_id;
};
typedef struct start_game_response start_game_response;

#define GAME_FORCA 1344357464
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define start_game 10
extern  start_game_response * start_game_1(game *, CLIENT *);
extern  start_game_response * start_game_1_svc(game *, struct svc_req *);
extern int game_forca_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define start_game 10
extern  start_game_response * start_game_1();
extern  start_game_response * start_game_1_svc();
extern int game_forca_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_game (XDR *, game*);
extern  bool_t xdr_start_game_response (XDR *, start_game_response*);

#else /* K&R C */
extern bool_t xdr_game ();
extern bool_t xdr_start_game_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FORCA_H_RPCGEN */
