/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FORCA_H_RPCGEN
#define _FORCA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct values {
	float n1;
	float n2;
};
typedef struct values values;

#define MATH 200
#define VERSION 100

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  float * sum_100(values *, CLIENT *);
extern  float * sum_100_svc(values *, struct svc_req *);
extern int math_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  float * sum_100();
extern  float * sum_100_svc();
extern int math_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FORCA_H_RPCGEN */
