/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "something.h"


void
teste_1(char *host)
{
	CLIENT *clnt;
	game_response  *result_1;
	game  start_game_1_arg;
	game_response  *result_2;
	game  trying_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTE, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = start_game_1(&start_game_1_arg, clnt);
	if (result_1 == (game_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	trying_1_arg.player_trying = 'H';
	result_2 = trying_1(&trying_1_arg, clnt);
	if (result_2 == (game_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	teste_1 (host);
exit (0);
}
